import { mkdirSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { expect, test } from './fixtures'
import { ensureExported, ensureSetUpAndSignedIn, ensureSolvedImage, imagesTitled } from './helpers'

// README screenshots (#159), regenerated by `make screenshots` from the e2e Orion fixture and the
// fake nova, so they never carry a real sky, a real key or a real title. Not a test: it runs only
// when E2E_SCREENSHOTS=1, after the same setup/solve/export story the suite uses.
const OUT = resolve(fileURLToPath(new URL('..', import.meta.url)), '..', 'docs', 'screenshots')

test.skip(process.env.E2E_SCREENSHOTS !== '1', 'set E2E_SCREENSHOTS=1 (make screenshots)')

test.use({ viewport: { width: 1280, height: 800 }, deviceScaleFactor: 1 })

test('capture the README screenshots', async ({ page, browser }) => {
  mkdirSync(OUT, { recursive: true })
  await ensureSetUpAndSignedIn(page)
  // The suite's "E2E sky" title would show in every header; the screenshots carry the product name.
  expect((await page.request.put('/api/config', { data: { site_title: 'AstroCaption' } })).status()).toBe(200)

  const card = await ensureSolvedImage(page, 'Orion')
  await ensureExported(card, 'Orion')
  const [image] = await imagesTitled(page.request, 'Orion')
  expect(image).toBeTruthy()
  if (!image!.published) {
    await card.getByRole('button', { name: 'Publish' }).click()
    await expect(card.getByText('Published')).toBeVisible()
  }

  // The editor, fitted, with the Objects tab open.
  await card.getByRole('link', { name: 'Edit' }).click()
  await expect(page).toHaveURL(/\/images\/[0-9a-f-]+$/)
  await page.waitForFunction(() => window.__astrocaptionEditor?.labelPositions !== undefined)
  await page.getByRole('button', { name: 'Fit' }).click()
  await page.getByRole('tab', { name: 'Objects' }).click()
  await expect(page.locator('.object-list input[type=checkbox]').first()).toBeVisible()
  await page.waitForTimeout(500) // let the canvas settle after Fit
  await page.screenshot({ path: resolve(OUT, 'editor.png') })

  // The published image as a signed-out visitor sees it.
  const visitor = await browser.newContext({ viewport: { width: 1280, height: 800 }, deviceScaleFactor: 1 })
  const pub = await visitor.newPage()
  try {
    await pub.goto(`/gallery/${image!.id}`)
    const galleryCard = pub.locator('.gallery-card')
    await expect(galleryCard).toBeVisible()
    // Hovering reveals the annotated preview (SPEC § 5.5); that is the picture worth showing.
    await galleryCard.hover()
    const overlay = galleryCard.locator('img.overlay')
    await expect(overlay).toHaveCSS('opacity', '1')
    await expect.poll(() => overlay.evaluate((e: HTMLImageElement) => e.naturalWidth)).toBeGreaterThan(0)
    await pub.screenshot({ path: resolve(OUT, 'gallery-image.png'), fullPage: true })
  } finally {
    await visitor.close()
  }
})
